name: My first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting step
        run: | 
          echo "Hello World!"
          echo "Im computing really noting"
      - name: Good Bye step
        run: echo "Done - Bye"
